#!/usr/local/bin/python
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
# SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
# DAMAGE.
# ENTSO-E 2020 Authors: Lars-Ola Österlund
#
# The script runs the model validation using the Java wrapper
# The xmi files to process should be in the "xmi" folder

import sys, os, glob, re, time
wd = os.getcwd()
if os.path.exists("xmi"):
    command = "java -Xms16000m -Xmx16000m -jar target/EmfValidatorJavaWrapper-1.0-jar-with-all-dependencies.jar"
    os.system(command)
else:
    print ("[" + time.strftime("%Y-%m-%d %H:%M:%S") + "] [INFO   ] No xmi files found, check 'inputs' directory")
